### ISSUE TITLE
Randomly distributed results were returned

### ISSUE THREAD

**Issue by YubinXie** [sg-s/Multicore-TSNE#5]
I installed this version of mc tsne in Mac OS. It is fast, but it gives random results (all points mixed together, just like a random distribution ). 
Mac OS 13.5, python 3.6.

**Comment by sg-s** [comment]
why doesn't it make sense? what was your input?

**Comment by YubinXie** [comment]
I used my own data, results as attached. First one is Linux version results and the second one is Mac (this version). The second one looks like a random distribution. 
![linux](https://user-images.githubusercontent.com/16257776/43039350-7115dfec-8cf9-11e8-84ec-67186fe01a8e.png)
![mac](https://user-images.githubusercontent.com/16257776/43039351-711ed71e-8cf9-11e8-9351-86d1b001908b.png)

I tried this Mac version on Minist data, it works good. So I guess there are some changes in this Mac version compared to the Linux version, that makes it do not work for some data (e.g. sparse data).

**Comment by sg-s** [comment]
same code, run on linux and mac os? what is the colour in the second plot?

**Comment by YubinXie** [comment]
Both were ran in Mac OS. One used the original Multicore-TSNE, which is designed for Linux, the other used this Multicore-TSNE, which is designed for Mac OS. I have 6-dimension data, and the color presents the values in one of the dimension.

**Comment by sg-s** [comment]
OK, so it looks like you're colouring one based on the other. there's no reason for the precise identities of the points to be identical across multiple embeddings. if you look at the two figures, you will see that one is a rotation and distortion of the other. this is expected -- you'll see the same thing if you run it multiple times. 

there's no implementation difference b/w the different versions

**Comment by YubinXie** [comment]
The point here is not the shape, but clustering in all my plot of 6 dimension. There is no clustering showing up. All the 6 dimension shows randomly distribution. 
Also, it takes Linux version  5min to finish running, this version takes 1min. I feel that it is not doing anything.

**Comment by sg-s** [comment]
have you tried this on MNIST or something standard? It seems to work for me on synthetic data and I'm struggling to understand why you think it doesn't work
